-- MySQL Script generated by MySQL Workbench
-- Tue Jan 25 10:10:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provincies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`provincies` (
  `idprovincia` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprovincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`localitats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`localitats` (
  `idlocalitat` INT(10) UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `provincies_idprovincia` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idlocalitat`),
  CONSTRAINT `fk_localitats_provincies1`
    FOREIGN KEY (`provincies_idprovincia`)
    REFERENCES `pizzeria`.`provincies` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_localitats_provincies1_idx` ON `pizzeria`.`localitats` (`provincies_idprovincia` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `idclient` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(200) NOT NULL,
  `adreça` VARCHAR(200) NULL,
  `codi_postal` VARCHAR(5) NULL,
  `telefon` VARCHAR(12) NOT NULL,
  `localitats_idlocalitat` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idclient`),
  CONSTRAINT `fk_clients_localitats1`
    FOREIGN KEY (`localitats_idlocalitat`)
    REFERENCES `pizzeria`.`localitats` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clients_localitats1_idx` ON `pizzeria`.`clients` (`localitats_idlocalitat` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`botigues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botigues` (
  `idbotiga` INT(10) UNSIGNED NOT NULL,
  `adreça` VARCHAR(200) NULL,
  `codipostal` VARCHAR(5) NULL,
  `localitats_idlocalitat` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idbotiga`),
  CONSTRAINT `fk_botigues_localitats1`
    FOREIGN KEY (`localitats_idlocalitat`)
    REFERENCES `pizzeria`.`localitats` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_botigues_localitats1_idx` ON `pizzeria`.`botigues` (`localitats_idlocalitat` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `idempleat` INT(10) UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NULL,
  `cognoms` VARCHAR(100) NULL,
  `nif` VARCHAR(9) NULL,
  `telefon` VARCHAR(12) NULL,
  `tipus` ENUM('cuiner', 'repartidor') NULL,
  `botigues_idbotiga` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idempleat`),
  CONSTRAINT `fk_empleats_botigues1`
    FOREIGN KEY (`botigues_idbotiga`)
    REFERENCES `pizzeria`.`botigues` (`idbotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empleats_botigues1_idx` ON `pizzeria`.`empleats` (`botigues_idbotiga` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`entregues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`entregues` (
  `identrega` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_repartidor` VARCHAR(45) NULL,
  `datahora_entrega` DATETIME NULL,
  `empleats_idempleat` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`identrega`),
  CONSTRAINT `fk_entregues_empleats1`
    FOREIGN KEY (`empleats_idempleat`)
    REFERENCES `pizzeria`.`empleats` (`idempleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_entregues_empleats1_idx` ON `pizzeria`.`entregues` (`empleats_idempleat` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`comandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comandes` (
  `idcomanda` INT(10) UNSIGNED NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `tipus` ENUM('Recollida', 'Domicili') NOT NULL,
  `cantitat` INT NOT NULL,
  `preu_total` INT NOT NULL,
  `clients_idclient` INT(10) UNSIGNED NOT NULL,
  `entregues_identrega` INT UNSIGNED NULL,
  `botigues_idbotiga` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idcomanda`),
  CONSTRAINT `fk_comandes_clients1`
    FOREIGN KEY (`clients_idclient`)
    REFERENCES `pizzeria`.`clients` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comandes_entregues1`
    FOREIGN KEY (`entregues_identrega`)
    REFERENCES `pizzeria`.`entregues` (`identrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comandes_botigues1`
    FOREIGN KEY (`botigues_idbotiga`)
    REFERENCES `pizzeria`.`botigues` (`idbotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comandes_clients1_idx` ON `pizzeria`.`comandes` (`clients_idclient` ASC);

CREATE INDEX `fk_comandes_entregues1_idx` ON `pizzeria`.`comandes` (`entregues_identrega` ASC);

CREATE INDEX `fk_comandes_botigues1_idx` ON `pizzeria`.`comandes` (`botigues_idbotiga` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categories` (
  `idcategoria` INT(10) UNSIGNED NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productes` (
  `idproducte` INT(10) UNSIGNED NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `descripcio` VARCHAR(200) NOT NULL,
  `imatge` VARCHAR(45) NULL,
  `preu` INT UNSIGNED NOT NULL,
  `tipus` ENUM('pizzes', 'hamburgueses', 'begudes') NOT NULL,
  `categories_idcategoria` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`idproducte`),
  CONSTRAINT `fk_productes_categories1`
    FOREIGN KEY (`categories_idcategoria`)
    REFERENCES `pizzeria`.`categories` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productes_categories1_idx` ON `pizzeria`.`productes` (`categories_idcategoria` ASC);


-- -----------------------------------------------------
-- Table `pizzeria`.`descripcio_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`descripcio_comanda` (
  `comandes_idcomanda` INT(10) UNSIGNED NOT NULL,
  `productes_idproducte` INT(10) UNSIGNED NOT NULL,
  `preu_unitat` INT NULL,
  `quantitat` INT NULL,
  `desconte` VARCHAR(45) NULL,
  PRIMARY KEY (`comandes_idcomanda`, `productes_idproducte`),
  CONSTRAINT `fk_comandes_has_productes_comandes1`
    FOREIGN KEY (`comandes_idcomanda`)
    REFERENCES `pizzeria`.`comandes` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comandes_has_productes_productes1`
    FOREIGN KEY (`productes_idproducte`)
    REFERENCES `pizzeria`.`productes` (`idproducte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comandes_has_productes_productes1_idx` ON `pizzeria`.`descripcio_comanda` (`productes_idproducte` ASC);

CREATE INDEX `fk_comandes_has_productes_comandes1_idx` ON `pizzeria`.`descripcio_comanda` (`comandes_idcomanda` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
